### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by anabranch** [python-boot-camp/D01#30]
Might help you out:

https://github.com/MIDS-Python-Bridge-Course/Course-Overview

you could probably cannabalize the command line as well as the git lectures. Spent a fair amount of time working on them and they will likely be relevant.

**Comment by danielsgriffin** [comment]
I glanced at it. I'll look more later. We have been using git and GitHub every day! They're learning (and me too) and it's awesome. I'll definitely look through for myself and probably share the links, but probably not going to assign them. I'm trying to expose them to CLI and git as we go but we have so much Python to cover before the place-in as well.

Thanks again.

**Comment by anabranch** [comment]
didn't realize you had already started! Good stuff, just wanted to give you a heads up to see if it was relevant.
